### ISSUE TITLE
npm run watch  error:

### ISSUE THREAD

**Issue by huangguofei** [scottcharlesworth/laravel-mix-polyfill#11]
Laravel Mix Version: 1.0
Node Version: v10.15.1
NPM Version: 6.9.0
OS: window 7

mix.extend('polyfill', new Polyfill());
    ^

TypeError: mix.extend is not a function

**Comment by scottcharlesworth** [comment]
This extension does not work with any Laravel Mix version less than v4. You'll need to update your version of Mix to use it.

Laravel Mix v4 is listed as a peer dependency in `package.json` and a message will have displayed on the command line when you installed this extension.

**Comment by huangguofei** [comment]
Thank you very much. How do I turn off strict mode?
How to shut down ?   ->  "use strict";
