### ISSUE TITLE
README.MD polyfill example code wrong

### ISSUE THREAD

**Issue by ponichWebKnight** [scottcharlesworth/laravel-mix-polyfill#13]
.polyfill({
      enabled: true,
      useBuiltIns: "usage",
      targets: {"firefox": "50", "ie": 11} // shoud be "11"
});

**Comment by scottcharlesworth** [comment]
@ponichWebKnight I've tested the example and confirmed it still works correctly when the value is a number.

Are you having issues?

**Comment by ponichWebKnight** [comment]
Not anymore - some bugs with a webpack version. Now works perfectly!
