### ISSUE TITLE
babel-polyfill deprecated

### ISSUE THREAD

**Issue by 3zzy** [scottcharlesworth/laravel-mix-polyfill#16]
https://babeljs.io/docs/en/babel-polyfill

> As of Babel 7.4.0, this package has been deprecated in favor of directly including core-js/stable (to polyfill ECMAScript features) and regenerator-runtime/runtime (needed to use transpiled generator functions):
> 
> ```
> import "core-js/stable";
> import "regenerator-runtime/runtime";
> 
> 
> ```

**Comment by scottcharlesworth** [comment]
[Version 2](/scottcharlesworth/laravel-mix-polyfill/tree/v2) is on the way 😃

**Comment by harrygulliford** [comment]
@scottcharlesworth Any news on v2?

**Comment by scottcharlesworth** [comment]
@harrygulliford I'm just testing v2 now. You're welcome to try v2 yourself by changing your `package.json` to:
```js
"laravel-mix-polyfill": "scottcharlesworth/laravel-mix-polyfill#v2",
```
