### ISSUE TITLE
Laravel webpack and polyfill not working in IE 11

### ISSUE THREAD

**Issue by DLO33** [scottcharlesworth/laravel-mix-polyfill#17]
So I've developed an app using Laravel and Vue, and trying to get it backwards compatible with IE (11) but not having much luck.

It seems that mix-polyfill is adding the correct polyfills however IE is still not rendering the app due to the follwing error.

Is there something else that I am missing?

![image](https://user-images.githubusercontent.com/35256407/61578657-d23bcd00-ab3d-11e9-96ed-8291b2837a7f.png)

![image](https://user-images.githubusercontent.com/35256407/61578663-dcf66200-ab3d-11e9-91a7-65bc432f302a.png)

**package.json**
devDependencies
"laravel-mix": "^4.0.7",
"laravel-mix-polyfill": "^1.1.0",

dependencies
"@babel/core": "^7.5.5",
"@babel/polyfill": "^7.4.4",
 "@babel/preset-env": "^7.5.5",

**webpack.mix.js**
> const mix = require("laravel-mix");
> require("laravel-mix-polyfill");
> 
> mix.js("resources/js/app.js", "public/js")
>     .sass("resources/sass/app.scss", "public/css")
>     .polyfill({
>         enabled: true,
>         debug: true,
>         useBuiltIns: "usage",
>         targets: { firefox: "50", ie: 11 }
>     });

**Debug output**
Using targets:
{
  "firefox": "50",
  "ie": "11"
}

Using modules transform: auto

Using plugins:
  transform-template-literals { "ie":"11" }
  transform-literals { "firefox":"50", "ie":"11" }
  transform-function-name { "firefox":"50", "ie":"11" }
  transform-arrow-functions { "ie":"11" }
  transform-classes { "ie":"11" }
  transform-object-super { "ie":"11" }
  transform-shorthand-properties { "ie":"11" }
  transform-duplicate-keys { "ie":"11" }
  transform-computed-properties { "ie":"11" }
  transform-for-of { "firefox":"50", "ie":"11" }
  transform-sticky-regex { "ie":"11" }
  transform-dotall-regex { "firefox":"50", "ie":"11" }
  transform-unicode-regex { "ie":"11" }
  transform-spread { "ie":"11" }
  transform-parameters { "firefox":"50", "ie":"11" }
  transform-destructuring { "firefox":"50", "ie":"11" }
  transform-block-scoping { "firefox":"50", "ie":"11" }
  transform-typeof-symbol { "ie":"11" }
  transform-new-target { "ie":"11" }
  transform-regenerator { "firefox":"50", "ie":"11" }
  transform-exponentiation-operator { "firefox":"50", "ie":"11" }
  transform-async-to-generator { "firefox":"50", "ie":"11" }
  proposal-async-generator-functions { "firefox":"50", "ie":"11" }
  proposal-object-rest-spread { "firefox":"50", "ie":"11" }
  proposal-unicode-property-regex { "firefox":"50", "ie":"11" }
  proposal-json-strings { "firefox":"50", "ie":"11" }
  proposal-optional-catch-binding { "firefox":"50", "ie":"11" }
  transform-named-capturing-groups-regex { "firefox":"50", "ie":"11" }

Using polyfills with `usage` option:

[C:\xampp\htdocs\locateourhome\resources\js\app.js] Based on your code and targets, core-js polyfills were not added.                                         10% building 4/6 modules 2 active C:\xampp\htdocs\locateourhome\node_modules\babel-loader\lib\index.js??ref--4-0!C:\xampp\htdocs\locateourhome\resources\js\routes.js
[C:\xampp\htdocs\locateourhome\resources\js\routes.js] Based on your code and targets, core-js polyfills were not 10% building 8/13 modules 5 active C:\xampp\htdocs\locateourhome\node_modules\babel-loader\lib\index.js??ref--4-0!C:\xampp\htdocs\locateourhome\resources\js\components\mixins\GlobalFunctions.js
[C:\xampp\htdocs\locateourhome\resources\js\bootstrap.js] Based on your code and targ 11% building 9/13 modules 4 active C:\xampp\htdocs\locateourhome\node_modules\babel-loader\lib\index.js??ref--4-0!C:\xampp\htdocs\locateourhome\resources\js\components\mixins\GlobalFunctions.js[C:\xampp\htdocs\locateourhome\resources\js\helpers\httpInterceptor.js] Added following core-js polyfills:
  es6.object.to-string { "firefox":"50", "ie":"11" }
  es6.promise { "ie":"11" }                                                           11% building 10/13 modules 3 active C:\xampp\htdocs\locateourhome\node_modules\babel-loader\lib\index.js??ref--4-0!C:\xampp\htdocs\locateourhome\resources\js\components\mixins\GlobalFunctions.js
[C:\xampp\htdocs\locateourhome\resources\js\store.js] Based on your code and targets 11% building 11/14 modules 3 active C:\xampp\htdocs\locateourhome\node_modules\vue\dist\vue.common.dev.js
[C:\xampp\htdocs\locateourhome\resources\js\components\mixins\GlobalFunctions.js] Added following core-js polyfills:
  es6.regexp.replace { "ie":"11" }
  es6.regexp.constructor { "ie":"11" }
  es6.object.to-string { "firefox":"50", "ie":"11" }
  es6.regexp.to-string { "ie":"11" }
  es6.promise { "ie":"11" }
  es6.symbol { "firefox":"50", "ie":"11" }
  es7.symbol.async-iterator { "firefox":"50", "ie":"11" }                                                                                                                     26% building 141/166 modules 25 active ...me\resources\js\components\Auth\ForgotPasswordComponent.vue?vue&type=script&lang=js&
[C:\xampp\htdocs\locateourhome\resources\js\components\PropertyRequests\PropertyRequestSummaryComponent.vue] Added following core-js polyfill:
  es6.array.find-index { "ie":"11" }

[C:\xampp\htdocs\locateourhome\resources\js\components\PropertyRequests\PropertyRequestMatchComponent.vue] Based on your code and targets, core-js polyf 27% building 142/167 modules 25 active ...me\resources\js\components\Auth\ForgotPasswordComponent.vue?vue&type=script&lang=js&[C:\xampp\htdocs\locateourhome\resources\js\components\PropertyRequests\PropertyRequestCreateComponent.vue] Added following core-js polyfills:
  es6.object.keys { "ie":"11" }
  es6.object.to-string { "firefox":"50", "ie":"11" }
  es6.array.iterator { "ie":"11" }
  web.dom.iterable { "firefox":"50", "ie":"11" }
  es6.array.find { "ie":"11" }
  es6.symbol { "firefox":"50", "ie":"11" }
  es7.object.get-own-property-descriptors { "ie":"11" }                                                                                                  27% building 143/168 modules 25 active ...me\resources\js\components\Auth\ForgotPasswordComponent.vue?vue&type=script&lang=js&[C:\xampp\htdocs\locateourhome\resources\js\components\Homes\HomeSummaryComponent.vue] Added following core-js polyfills:
  es6.array.find-index { "ie":"11" }
  es6.regexp.replace { "ie":"11" }

[C:\xampp\htdocs\locateourhome\resources\js\components\Homes\HomeCreateComponent.vue] Added following core-js polyfills:
  es6.object.keys { "ie":"11" }
  es6.object.to-string { "firefox":"50", "ie":"11" }
  es6.array.iterator { "ie":"11" }
  web.dom.iterable { "firefox":"50", "ie":"11" }
  es6.array.from { "ie":"11" }
  es6.string.iterator { "ie":"11" }
  es6.string.includes { "ie":"11" }
  es7.array.includes { "ie":"11" }
  es6.promise { "ie":"11" }
  es6.array.find { "ie":"11" }
  es6.symbol { "firefox":"50", "ie":"11" }
  es7.object.get-own-property-descriptors { "ie":"11" }                                                                                                  27% building 144/169 modules 25 active ...me\resources\js\components\Auth\ForgotPasswordComponent.vue?vue&type=script&lang=js&[C:\xampp\htdocs\locateourhome\resources\js\components\Auth\ResetPasswordComponent.vue] Based on your code and targets, core-js polyfills were not added.

[C:\xampp\htdocs\locateourhome\resources\js\components\User\RentalApplicationComponent.vue] Added following core-js polyfills:
  es7.array.includes { "ie":"11" }
  es6.string.includes { "ie":"11" }
  es6.function.name { "ie":"11" }
  es6.array.from { "ie":"11" }
  es6.string.iterator { "ie":"11" }
  es6.regexp.replace { "ie":"11" }
  es6.object.keys { "ie":"11" }
  es6.object.to-string { "firefox":"50", "ie":"11" }
  es6.array.iterator { "ie":"11" }
  web.dom.iterable { "firefox":"50", "ie":"11" }
  es7.object.values { "ie":"11" }
  es6.promise { "ie":"11" }

[C:\xampp\htdocs\locateourhome\resources\js\components\User\RentalApplicationComponent.vue] Based on your code and targets, added regenerator-runtime.   27% building 144/172 modules 28 active ...eourhome\resources\js\components\Auth\RegisterComponent.vue?vue&type=script&lang=js&[C:\xampp\htdocs\locateourhome\resources\js\components\Auth\ForgotPasswordComponent.vue] Based on your code and targets, core-js polyfills were not adde 27% building 145/173 modules 28 active ...eourhome\resources\js\components\Auth\RegisterComponent.vue?vue&type=script&lang=js&[C:\xampp\htdocs\locateourhome\resources\js\components\Auth\LogoutComponent.vue] Based on your code and targets, core-js polyfills were not added.       27% building 145/174 modules 29 active ...me\resources\js\components\User\PasswordChangeComponent.vue?vue&type=script&lang=js&[C:\xampp\htdocs\locateourhome\resources\js\components\Auth\LoginComponent.vue] Based on your code and targets, core-js polyfills were not added.

[C:\xampp\htdocs\locateourhome\resources\js\components\Auth\RegisterComponent.vue] Based on your code and targets, core-js polyfills were not added.     27% building 146/176 modules 30 active ...ourhome\resources\js\components\User\MyDetailsComponent.vue?vue&type=script&lang=js&[C:\xampp\htdocs\locateourhome\resources\js\components\User\PasswordChangeComponent.vue] Based on your code and targets, core-js polyfills were not adde 27% building 147/177 modules 30 active ...ourhome\resources\js\components\User\MyDetailsComponent.vue?vue&type=script&lang=js&[C:\xampp\htdocs\locateourhome\resources\js\components\User\MyDetailsComponent.vue] Based on your code and targets, core-js polyfills were not added.    27% building 147/178 modules 31 active ...eourhome\resources\js\components\User\FeedbackComponent.vue?vue&type=script&lang=js&[C:\xampp\htdocs\locateourhome\resources\js\components\User\FeedbackComponent.vue] Based on your code and targets, core-js polyfills were not added.     27% building 147/179 modules 32 active ...pp\htdocs\locateourhome\resources\js\components\Nav\Nav.vue?vue&type=script&lang=js&[C:\xampp\htdocs\locateourhome\resources\js\components\Nav\Nav.vue] Based on your code and targets, core-js polyfills were not added.                    66% building 578/610 modules 32 active ...ourhome\resources\js\components\User\DashboardComponent.vue?vue&type=script&lang=js&[C:\xampp\htdocs\locateourhome\resources\js\components\User\DashboardComponent.vue] Based on your code and targets, core-js polyfills were not added.    66% building 580/612 modules 32 active ...eourhome\resources\js\components\Generic\ModalComponent.vue?vue&type=script&lang=js&[C:\xampp\htdocs\locateourhome\resources\js\components\Generic\ModalComponent.vue] Based on your code and targets, core-js polyfills were not added.     66% building 582/614 modules 32 active ...rhome\resources\js\components\User\UserDetailsComponent.vue?vue&type=script&lang=js&[C:\xampp\htdocs\locateourhome\resources\js\components\User\UserDetailsComponent.vue] Based on your code and targets, core-js polyfills were not added.  66% building 587/619 modules 32 active ...docs\locateourhome\resources\js\components\AppComponent.vue?vue&type=script&lang=js&[C:\xampp\htdocs\locateourhome\resources\js\components\AppComponent.vue] Added following core-js polyfills:
  es6.array.from { "ie":"11" }
  es6.string.iterator { "ie":"11" }                                                                                                                      67% building 599/624 modules 25 active ...ocateourhome\resources\js\components\Generic\FileUpload.vue?vue&type=script&lang=js&[C:\xampp\htdocs\locateourhome\resources\js\components\Generic\FileUpload.vue] Added following core-js polyfills:
  es6.object.to-string { "firefox":"50", "ie":"11" }
  es6.promise { "ie":"11" }
  es6.array.from { "ie":"11" }
  es6.string.iterator { "ie":"11" }
  es6.function.name { "ie":"11" }                                                                                                                        67% building 610/633 modules 23 active ...e\resources\js\components\Generic\FormControlsComponent.vue?vue&type=script&lang=js&[C:\xampp\htdocs\locateourhome\resources\js\components\Generic\FormControlsComponent.vue] Added following core-js polyfill:
  es6.array.find-index { "ie":"11" }                                                                                                                     67% building 651/678 modules 27 active ...me\resources\js\components\Generic\MapComponent.vue?vue&type=style&index=0&lang=css&[C:\xampp\htdocs\locateourhome\resources\js\components\Generic\MapComponent.vue] Added following core-js polyfills:
  es6.object.to-string { "firefox":"50", "ie":"11" }
  es6.promise { "ie":"11" }                                                                                                                              66% building 666/710 modules 44 active ...\RentalApplicationModal.vue?vue&type=style&index=1&id=6e2c1587&scoped=true&lang=css&[C:\xampp\htdocs\locateourhome\resources\js\components\Homes\RentalApplicationModal.vue] Added following core-js polyfills:
  es6.function.name { "ie":"11" }
  es6.object.keys { "ie":"11" }
  es6.object.to-string { "firefox":"50", "ie":"11" }
  es6.array.iterator { "ie":"11" }
  web.dom.iterable { "firefox":"50", "ie":"11" }                                                                                                         66% building 685/732 modules 47 active C:\xampp\htdocs\locateourhome\node_modules\core-js\modules\_iter-step.js[C:\xampp\htdocs\locateourhome\resources\js\helpers\fileUpload\utils.js] Added following core-js polyfills:
  es6.object.to-string { "firefox":"50", "ie":"11" }
  es6.promise { "ie":"11" }                                                                                                                                             66% building 686/732 modules 46 active C:\xampp\htdocs\locateourhome\node_modules\core-js\modules\_iter-step.js[C:\xampp\htdocs\locateourhome\resources\js\helpers\fileUpload\file-upload.fake.service.js] Added following core-js polyfills:
  es6.function.name { "ie":"11" }
  es6.string.iterator { "ie":"11" }
  es6.object.to-string { "firefox":"50", "ie":"11" }
  es6.array.iterator { "ie":"11" }
  web.dom.iterable { "firefox":"50", "ie":"11" }
  es6.promise { "ie":"11" }
  es6.regexp.split { "ie":"11" }

**Comment by scottcharlesworth** [comment]
@DLO33 the conversion from shorthand to longhand is done by Babel, not Polyfill. I can get my shorthand method definitions to work in IE11 without Polyfill at all - so this is a strange one - but I'll try to help.

One solution is just to use longhand, like in the [Vue manual](https://vuejs.org/v2/guide/computed.html):
```js
computed: {
   styles: function () {
      return {
         // Something
      }
   },
}
```

Is your component in a separate file, marked with the extension `.vue`, and pulled into `app.js` with:
```js
Vue.component('example-component', require('./components/ExampleComponent.vue').default);
```
or is it directly in the `app.js` file?

**Comment by DLO33** [comment]
@scottcharlesworth, I'm not wanting to go back through all my code and refactor it. So want to try and traspile it. All my components are pulled into the vue app like so:

> import ExampleComponent from "./components/ExampleComponent";
> Vue.component("ExampleComponent", ExampleComponent);

**Comment by DLO33** [comment]
I've closed this as I believe my question lies with laravel mix.
https://github.com/JeffreyWay/laravel-mix/issues/2174
