### ISSUE TITLE
Update laravel-mix Peer Dependency to v5.0.0

### ISSUE THREAD

**Issue by MannikJ** [scottcharlesworth/laravel-mix-polyfill#20]
This package's latest version has a peer dependency on `laravel-mix": "^4.0.0`. So npm always warns when using with laravel-mix >=v5.0.0. As far as I see everything is running fine, so you might just update the dependency. 
Or are there any potential problems?

**Comment by scottcharlesworth** [comment]
Thanks for letting me know. I'll run some tests and update the dependency if everything's OK.

**Comment by scottcharlesworth** [comment]
The peer depencency has been updated in v1.1.1. Thanks.
