### ISSUE TITLE
TypeError: mix.extend is not a function

### ISSUE THREAD

**Issue by Dev-El-badry** [scottcharlesworth/laravel-mix-polyfill#26]
mix.extend('polyfill', new Polyfill());

show error when command run " npm run watch "

webpack.mix.js :

let mix = require('laravel-mix');
require('laravel-mix-polyfill');

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .polyfill({
      enabled: true,
      useBuiltIns: "usage",
      targets: {"firefox": "50", "ie": 11}
   });

**Comment by scottcharlesworth** [comment]
@Dev-El-badry what version of Laravel Mix are you using?

**Comment by Dev-El-badry** [comment]
"devDependencies": {
        "axios": "^0.17",
        "cross-env": "^5.1",
        "jquery": "^3.5.1",
        "laravel-mix": "^1.0",
        "lodash": "^4.17.4",
        "vue": "^2.5.7"
    },

**Comment by Dev-El-badry** [comment]
SOLVED  !!
Update my version laravel-mix to the latest version and it SOLVED
