### ISSUE TITLE
Polyfills do not work with `.extract()`

### ISSUE THREAD

**Issue by KorvinSzanto** [scottcharlesworth/laravel-mix-polyfill#29]
If you use mix.extract() to extract vendor files polyfills don't seem to apply to the outputted vendors.js file. My specific situation was trying to polyfill the spread operator for legacy edge, no matter what I tried the vendor.js file didn't get the polyfills. Thankfully I was able to just stop using .extract to get around this but that's not ideal.

**Comment by scottcharlesworth** [comment]
@KorvinSzanto it is interesting that you are able to get the vendor libraries to polyfill by just omitting `.extract()` as the contents of `node_modules` is [excluded by default](https://github.com/JeffreyWay/laravel-mix/blob/v5/src/components/JavaScript.js#L72) in Laravel Mix.

However if you [see the answer here](https://github.com/scottcharlesworth/laravel-mix-polyfill/issues/18#issuecomment-656166177) you should be able to use `.extract()` and polyfill the vendor libraries.
