### ISSUE TITLE
After adding polyfill method forced to download vue-template-compiler

### ISSUE THREAD

**Issue by estissy** [scottcharlesworth/laravel-mix-polyfill#3]
After adding polyfill method to my chain in `webpack.mix.js` I am now forced to download `vue-template-compiler` while npm install/update. I make Laravel project without Vue.js and at start entered` php artisan preset none`

**Comment by scottcharlesworth** [comment]
Did it happen immediately after adding `.polyfill()`, or did you also install/upgrade to Laravel Mix 4?

I'm asking because there are closed issues in the Laravel Mix repo that reference this problem (JeffreyWay/laravel-mix#1877, JeffreyWay/laravel-mix#1916).

**Comment by mabasic** [comment]
I do not want to have vue-template-compiler dependency in my package.json file. Can it not be forced to install?

**Comment by rolandschuetz** [comment]
@mabasic vue-template-compiler is a dependency of Laravel Mix 4, not of this package.

So probably when you added this package your Laravel Mix got updated to 4 (minimum version for this package) and therefore Laravel Mix added the requirement.

You need to use `vue-template-compiler` for Vue when using Laravel Mix 4.

**Comment by mabasic** [comment]
@rolandschuetz I see, thank you for replying.

**Comment by mabasic** [comment]
@scottcharlesworth Can this be closed?

**Comment by scottcharlesworth** [comment]
@mabasic yes it can 👍
