### ISSUE TITLE
not working...?

### ISSUE THREAD

**Issue by dvlpr91** [scottcharlesworth/laravel-mix-polyfill#31]
I added it after installation, but ie11 still has problems.

**Comment by scottcharlesworth** [comment]
@dvlpr91 what specifically is it you're having problems with in IE11?

**Comment by dvlpr91** [comment]
> @dvlpr91 what specifically is it you're having problems with in IE11?


I'm trying to use "laravel", "inertiajs" and "svelte".

The error that occurs in "ie11" is very complex, so it is not easy to explain. However, by adding and setting "laravel-mix-polyfill", normal output is not performed in "ie11". ("polyfill" and "transpile" problems?, I don't know. If "laravel-mix-polyfill" is used, "ie11" and "chrome" always print the same?)

Also, it was confirmed that the simple es6 grammar(arrow function...) can be converted by laravel-mix without laravel-mix-polyfill, and works in ie11.
So, when do I need laravel-mix-polyfill?
