### ISSUE TITLE
laravel mix 6 support?

### ISSUE THREAD

**Issue by TheSnip3r** [scottcharlesworth/laravel-mix-polyfill#32]
It seems that it doesn't support mix 6.
would you support it please?

**Comment by scottcharlesworth** [comment]
I will take a look over the next 24 hours and see what needs to be done.

**Comment by scottcharlesworth** [comment]
@TheSnip3r would you be able to add the following to your `webpack.mix.js`:

```js
mix.extend('addTargets', function(webpackConfig) {
    webpackConfig.target = ['web', 'es5'];
});
```

And then add `.addTargets()` to the end of your chain.

For example:
```js
const mix = require('laravel-mix');

require('laravel-mix-polyfill');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel applications. By default, we are compiling the CSS
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.extend('addTargets', function(webpackConfig) {
    webpackConfig.target = ['web', 'es5'];
});

mix.js('resources/js/app.js', 'public/js')
    .postCss('resources/css/app.css', 'public/css', [
        //
    ])
    .polyfill()
    .addTargets();
```

It would help to confirm I've found the issue.

**Comment by TheSnip3r** [comment]
@scottcharlesworth 
Sorry maybe i didn't make myself clear. I'm not able to check as i cannot install it on Laravel Mix 6. I think the reason is this:

```
"peerDependencies": {
    "laravel-mix": "^4.0.0 || ^5.0.0"
  }
```

**Comment by scottcharlesworth** [comment]
@TheSnip3r Apologies, I assumed you had upgraded from Laravel Mix 5.
I think you can bypass dependency checking by adding the following directly to your `package.json`, and running `npm install` or `yarn install`:
```js
"laravel-mix-polyfill": "^2.0.0",
```

**Comment by TheSnip3r** [comment]
Thanks, it worked now and I don't know why! 
I tried it before and it displayed the error of dependency version for Mix "^4.0.0 || ^5.0.0".
However, it would be better to update this dependency.

**Comment by scottcharlesworth** [comment]
@TheSnip3r v3.0.0 has been released with Laravel v6 support.

Thank you for bringing it to my attention.
