### ISSUE TITLE
Module not found: Error: Can't resolve 'core-js/modules/es6.array.iterator'

### ISSUE THREAD

**Issue by sunscreem** [scottcharlesworth/laravel-mix-polyfill#6]
I did a clean `npm install` this morning and it seems like `es6.array.iterator` is no longer in the core-js package.

I'm a bit stuck on how to fix this.

I'm using this package purely to stop IE11 errors - maybe this is a bit overkill for that use case?

**Comment by ghost** [comment]
Having the same issue..

@sunscreem you can try this solution 
https://stackoverflow.com/a/52352875

**Comment by sunscreem** [comment]
Thanks @Rux77 - will give it a go.

**Comment by scottcharlesworth** [comment]
@sunscreem did the suggested solution work for you? When did this start?

I don't believe there's been any changes to `core-js@2.*` for a couple of months, and the [file referenced](https://github.com/zloirock/core-js/blob/v2/modules/es6.array.iterator.js) does still exist.

**Comment by scottcharlesworth** [comment]
@sunscreem I've been trying a few options to reproduce this error, and I have managed to find a scenario that does so.

Have you added `core-js@3.*` as a dependency in your project?

If so you will need to set the `corejs` option:

```js
mix.js('resources/js/app.js', 'public/js')
   .sass('resources/sass/app.scss', 'public/css')
   .polyfill({
      corejs: 3
   });
```

**Comment by sunscreem** [comment]
Perfect - that's it sorted :)
