### ISSUE TITLE
Module not found: Error: Can't resolve ...

### ISSUE THREAD

**Issue by Livijn** [scottcharlesworth/laravel-mix-polyfill#8]
Why am I getting this error when building? I am using Laravel Mix 4.0. I have ran `npm install --save core-js@2`.

> These dependencies were not found:
>
> * core-js/modules/es6.number.constructor in ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!../vue2-heropatterns/src/patterns/Pattern.vue?vue&type=script&lang=js&
>* core-js/modules/es6.regexp.replace in ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!../vue2-heropatterns/src/patterns/Pattern.vue?vue&type=script&lang=js&
>* core-js/modules/es6.symbol in ../object-to-formdata/index.js
>* core-js/modules/es7.symbol.async-iterator in ../object-to-formdata/index.js

Here in my _webpack.mix.js_:

    mix.js('resources/js/app.js', 'public/js')
    .polyfill({
        enabled: true,
        useBuiltIns: "usage",
        targets: {"firefox": "50", "ie": 11}
    })
    .sass('resources/sass/app.scss', 'public/css')
    .sass('resources/sass/pdf.scss', 'public/css')
    .version();

And _.babelrc_:

 ```
{
 "presets": [
    [
      "@babel/preset-env", {
      "targets": {
        "browsers": ["IE 11, last 2 versions"]
      }
    }
    ]
  ]
}
```

**Comment by scottcharlesworth** [comment]
Can you post the results of: `npm list --depth=0`

Also, using this plugin there's no need for the .babelrc you have there. You could just have this in your `webpack.mix.js`:

```js
mix.js('resources/js/app.js', 'public/js')
   .polyfill({
       targets: "IE 11, last 2 versions"
   })
   .sass('resources/sass/app.scss', 'public/css')
   .sass('resources/sass/pdf.scss', 'public/css')
   .version();
```

You could also instead create a `.browserslistrc` file at the root of your project with the following content:

```
IE 11
last 2 versions
```

.. and set
```js
.polyfill({targets: false})
```

That way your target browsers can also be seen by other plugins. But you could shorten the query to just:
`"last 2 versions"` as IE 11 is [covered already in that query](https://browserl.ist/?q=last+2+versions).

**Comment by Livijn** [comment]
Adding this to my webpack config solved the issue for me. Webpack was looking for the core-js in my symlinked folders as well.

```
 resolve: {
        symlinks: false
    },
```
